import Constants from 'expo-constants';

export const APP_NAME = 'PingPay';
export const APP_TAGLINE = 'Send money. Let them choose where it lands.';

/**
 * The public base URL of the PingPay web app. Envelope share links are
 * generated by the backend; this value is only used to build links locally
 * in mock mode. In production the backend always returns the full link.
 */
export const WEB_BASE_URL =
  process.env.EXPO_PUBLIC_WEB_URL ?? 'https://pingpay.app';

/**
 * Base URL of the FastAPI backend. Configure per environment via
 * EXPO_PUBLIC_API_URL. Falls back to the local dev server host.
 */
export const API_BASE_URL =
  process.env.EXPO_PUBLIC_API_URL ??
  (Constants.expoConfig?.hostUri
    ? `http://${String(Constants.expoConfig.hostUri).split(':')[0]}:8000`
    : 'http://localhost:8000');

/**
 * When true the app uses the in-memory mock service instead of performing
 * network requests. Automatically disabled as soon as a real API base URL is
 * provided in the environment.
 */
export const USE_MOCKS =
  (process.env.EXPO_PUBLIC_USE_MOCKS ?? 'true') === 'true' ||
  !process.env.EXPO_PUBLIC_API_URL;

export const currency = {
  code: 'GH₵',
  name: 'Ghana Cedi',
  locale: 'en-GH',
} as const;

export const AMOUNT = {
  min: 5,
  max: 500,
  step: 5,
  presets: [20, 50, 100, 200, 500],
} as const;

export const ENVELOPE = {
  /** Hours an unclaimed envelope stays valid. */
  expiryHours: 72,
} as const;
