export const APP_NAME = 'Envelope';
export const APP_TAGLINE = 'Send money. Let them choose where it lands.';
export const APP_WORDMARK = 'ENVELOPE';

/**
 * The public base URL of the Envelope web app. Envelope share links are
 * generated by the backend; this value is only used to build links locally
 * in mock mode. In production the backend always returns the full link.
 */
export const WEB_BASE_URL =
  process.env.EXPO_PUBLIC_WEB_URL ?? 'https://envlope.onrender.com';

/**
 * Base URL of the FastAPI backend, including the `/api` prefix that every
 * route lives under (`/api/auth/login`, `/api/envelopes`, ...).
 *
 * Override per environment with EXPO_PUBLIC_API_URL. The default targets the
 * host machine, which is what an iOS simulator and a web preview both see.
 * An Android emulator reaches the host at 10.0.2.2 instead, so set the env var
 * to `http://10.0.2.2:8000/api` when running there.
 */
export const API_BASE_URL =
  process.env.EXPO_PUBLIC_API_URL ?? 'https://envlope.onrender.com/api';

/**
 * When true the app uses the in-memory mock service instead of performing
 * network requests. Mocks are now opt-in, so a fresh checkout talks to the
 * real backend by default. Set EXPO_PUBLIC_USE_MOCKS=true to demo without one.
 */
export const USE_MOCKS = (process.env.EXPO_PUBLIC_USE_MOCKS ?? 'false') === 'true';

export const currency = {
  code: 'GH₵',
  name: 'Ghana Cedi',
  locale: 'en-GH',
} as const;

export const AMOUNT = {
  min: 5,
  max: 500,
  step: 5,
  presets: [20, 50, 100, 200, 500],
} as const;

export const ENVELOPE = {
  /** Hours an unclaimed envelope stays valid. */
  expiryHours: 72,
} as const;
